#!/bin/sh

if [ "$1" = "config" ] 
then

    # Graph settings
    echo "graph_category clickhouse"
    echo "graph_title Database Size"
    echo "graph_vlabel size"
    echo "graph_info Shows the amount of disk space taken by the data"
    echo "graph_args --base 1024 -l 0"

    # Series
    echo "size.label size"
    echo "size.draw AREA"

    exit 0

else

    DEFAULT_URL="http://localhost:8123/?readonly=1"
    URL="${CLICKHOUSE_URL:-$DEFAULT_URL}"
    SQL="SELECT 'size.value', sum(bytes) AS value FROM system.parts"
    echo $SQL | curl -sS $URL --data-binary @-

fi
