#!/bin/sh

if [ "$1" = "config" ] 
then

    # Graph settings
    echo "graph_category clickhouse"
    echo "graph_title Query Counts"
    echo "graph_vlabel queries per minute"
    echo "graph_info Shows the number of inserted and select queries"
    echo "graph_period minute"
    echo "graph_order insertquery selectquery"
    echo "graph_scale no"
    echo "graph_args --base 1000 -l 0"

    # Insert queries series
    echo "insertquery.type DERIVE"
    echo "insertquery.min 0"
    echo "insertquery.label insert"

    # Select queries series
    echo "selectquery.type DERIVE"
    echo "selectquery.min 0"
    echo "selectquery.label select"

    exit 0

else

    DEFAULT_URL="http://localhost:8123/?readonly=1"
    URL="${CLICKHOUSE_URL:-$DEFAULT_URL}"
    SQL="SELECT lower(event) || '.value', value FROM system.events WHERE event in ('InsertQuery', 'SelectQuery')"
    echo $SQL | curl $URL --data-binary @-

fi
